version: 0.2
env:
  variables:
    DOCKER_IMAGE_NAME: "playwright_automation:1.0"
phases:
  install:
    commands:
      - apt-get update -y && apt-get install -y git
  pre_build:
    commands:
      - echo "This is Codecommit Repo URL - $CODEBUILD_SOURCE_REPO_URL"
      - echo "Ready to run Tests"
  build:
    commands:
      - echo "inside build commands and printing all environment variables below"
      - printenv
      - echo `pwd`
      - pytest --html=reports/report.html ./tests/login_sauce.py
  artifacts:
  files:
    - reports/report.html
  name: Playwright-Test-Report